In [ ]:
import pandas as pd

# Đọc file dữ liệu gốc
df = pd.read_csv('dulieuxettuyendaihoc.csv')

# Xem thử 5 dòng đầu tiên xem dữ liệu lên đúng chưa
df.head()

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A

In [ ]:
# Xuất dữ liệu ra file CSV mới theo đúng tên yêu cầu
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)

In [ ]:
#Câu 1
data_cau1 = {
    'Tên Biến Số': ['Ma_HS', 'Gioi_tinh', 'Dan_toc', 'Khu_vuc', 'T1, L1, H1...', 'TBM1, TBM2...', 'XL1, XL2...'],
    'Ý Nghĩa': ['Mã học sinh / SBD', 'Giới tính thí sinh', 'Dân tộc của thí sinh', 'Khu vực xét tuyển', 'Điểm các môn lớp 10,11,12', 'Điểm trung bình môn', 'Xếp loại học lực'],
    'Phân Loại Dữ Liệu': ['Định tính (Qualitative)', 'Định tính (Qualitative)', 'Định tính (Qualitative)', 'Định tính (Qualitative)', 'Định lượng (Quantitative)', 'Định lượng (Quantitative)', 'Định tính (Qualitative)']
}

df_cau1 = pd.DataFrame(data_cau1)
print("--- ĐÁP ÁN CÂU 1: PHÂN LOẠI DỮ LIỆU ---")
display(df_cau1)

--- ĐÁP ÁN CÂU 1: PHÂN LOẠI DỮ LIỆU ---

     Tên Biến Số                    Ý Nghĩa          Phân Loại Dữ Liệu
0          Ma_HS          Mã học sinh / SBD    Định tính (Qualitative)
1      Gioi_tinh         Giới tính thí sinh    Định tính (Qualitative)
2        Dan_toc       Dân tộc của thí sinh    Định tính (Qualitative)
3        Khu_vuc          Khu vực xét tuyển    Định tính (Qualitative)
4  T1, L1, H1...  Điểm các môn lớp 10,11,12  Định lượng (Quantitative)
5  TBM1, TBM2...        Điểm trung bình môn  Định lượng (Quantitative)
6    XL1, XL2...           Xếp loại học lực    Định tính (Qualitative)

In [ ]:
#Câu 2
data_cau2 = {
    'Tên Biến Số': ['Ma_HS', 'Gioi_tinh', 'Dan_toc', 'Khu_vuc', 'T1, L1, H1...', 'TBM1, TBM2...', 'XL1, XL2...'],
    'Thang Đo Phù Hợp': ['Thang đo định danh (Nominal)', 'Thang đo định danh (Nominal)', 'Thang đo định danh (Nominal)', 'Thang đo thứ bậc (Ordinal)', 'Thang đo khoảng (Interval)', 'Thang đo khoảng (Interval)', 'Thang đo thứ bậc (Ordinal)'],
    'Giải Thích Lý Do': [
        'Chỉ dùng để định danh, không có tính hơn kém.',
        'Dùng để phân loại giới tính, không tính toán được.',
        'Dùng để phân loại các dân tộc, không mang tính thứ tự.',
        'Các khu vực có sự ưu tiên phân bậc rõ rệt (KV1 > KV2...).',
        'Là dữ liệu số, khoảng cách có ý nghĩa nhưng không có điểm 0 tuyệt đối.',
        'Là dữ liệu số tính toán từ điểm thành phần, thuộc thang đo khoảng.',
        'Các mức xếp loại có thứ tự cao thấp rõ ràng (Yếu < TB < Khá...).'
    ]
}

df_cau2 = pd.DataFrame(data_cau2)
print("--- ĐÁP ÁN CÂU 2: ĐỊNH NGHĨA THANG ĐO ---")
display(df_cau2)

--- ĐÁP ÁN CÂU 2: ĐỊNH NGHĨA THANG ĐO ---

,Tên Biến Số,Thang Đo Phù Hợp,Giải Thích Lý Do
0,Ma_HS,Thang đo định danh (Nominal),"Chỉ dùng để định danh, không có tính hơn kém."
1,Gioi_tinh,Thang đo định danh (Nominal),"Dùng để phân loại giới tính, không tính toán đ..."
2,Dan_toc,Thang đo định danh (Nominal),"Dùng để phân loại các dân tộc, không mang tính..."
3,Khu_vuc,Thang đo thứ bậc (Ordinal),Các khu vực có sự ưu tiên phân bậc rõ rệt (KV1...
4,"T1, L1, H1...",Thang đo khoảng (Interval),"Là dữ liệu số, khoảng cách có ý nghĩa nhưng kh..."
5,"TBM1, TBM2...",Thang đo khoảng (Interval),"Là dữ liệu số tính toán từ điểm thành phần, th..."
6,"XL1, XL2...",Thang đo thứ bậc (Ordinal),Các mức xếp loại có thứ tự cao thấp rõ ràng (Y...

In [ ]:
#Câu 3
import pandas as pd

# 1. Tải dữ liệu lên dataframe
df = pd.read_csv('dulieuxettuyendaihoc.csv')

# 2. In 10 dòng đầu tiên
print("--- 10 DÒNG ĐẦU TIÊN ---")
display(df.head(10))

# 3. In 10 dòng cuối cùng
print("\n--- 10 DÒNG CUỐI CÙNG ---")
display(df.tail(10))

--- 10 DÒNG ĐẦU TIÊN ---

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

--- 10 DÒNG CUỐI CÙNG ---

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [ ]:
#Câu 4
print("--- Thống kê cột dân tộc trước khi xử lý ---")
tan_so_dt = df['DT'].value_counts(dropna=False)
tan_suat_dt = df['DT'].value_counts(dropna=False, normalize=True) * 100

thong_ke_dt = pd.DataFrame({'Tần số': tan_so_dt, 'Tần suất (%)': tan_suat_dt})
display(thong_ke_dt)

# 2. Thay thế dữ liệu thiếu bằng số 0
df['DT'] = df['DT'].fillna(0)
print("\n-> Đã xử lý điền giá trị 0 cho các vị trí thiếu ở cột 'DT'.")

--- Thống kê cột dân tộc trước khi xử lý ---

     Tần số  Tần suất (%)
DT
NaN      97          97.0
1.0       2           2.0
6.0       1           1.0

-> Đã xử lý điền giá trị 0 cho các vị trí thiếu ở cột 'DT'.

In [ ]:
# CÂU 5: XỬ LÝ DỮ LIỆU THIẾU CHO BIẾN T1

# 1. Thống kê dữ liệu thiếu trước khi xử lý
print("Số lượng dữ liệu thiếu ở biến T1:", df['T1'].isnull().sum())

# 2. Tính giá trị trung bình (Mean) của cột T1
mean_t1 = df['T1'].mean()
print(f"Giá trị Mean của T1 dùng để điền: {mean_t1}")

# 3. Thay thế dữ liệu thiếu bằng Mean
df['T1'] = df['T1'].fillna(mean_t1)
print("-> Đã xử lý thiếu cho cột 'T1'.")

Số lượng dữ liệu thiếu ở biến T1: 0
Giá trị Mean của T1 dùng để điền: 5.946000000000001
-> Đã xử lý thiếu cho cột 'T1'.

In [ ]:
# CÂU 6: XỬ LÝ DỮ LIỆU THIẾU CHO CÁC BIẾN ĐIỂM CÒN LẠI BẰNG MEAN

# Tự động tìm các cột điểm số và điền giá trị mean của chính cột đó nếu bị thiếu
cac_cot_so = df.select_dtypes(include=['float64', 'int64']).columns

for col in cac_cot_so:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mean())

print("-> Đã xử lý toàn bộ dữ liệu thiếu cho các biến điểm số bằng phương pháp Mean.")

-> Đã xử lý toàn bộ dữ liệu thiếu cho các biến điểm số bằng phương pháp Mean.

In [ ]:
# CÂU 7: TÍNH ĐIỂM TRUNG BÌNH MÔN TBM1, TBM2, TBM3

# Áp dụng công thức theo yêu cầu đề bài
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T3']*2 + df['L3'] + df['H3'] + df['S3'] + df['V3']*2 + df['X3'] + df['D3'] + df['N3']) / 10

# Hiển thị thử 5 dòng đầu của kết quả vừa tính
display(df[['TBM1', 'TBM2', 'TBM3']].head())

   TBM1  TBM2  TBM3
0  7.00  7.54  7.06
1  4.69  5.47  4.70
2  5.77  5.38  4.33
3  6.21  5.20  6.03
4  6.50  6.36  7.01

In [ ]:
# CÂU 8: XẾP LOẠI HỌC LỰC XL1, XL2, XL3

# Định nghĩa hàm quy đổi điểm sang ký hiệu xếp loại
def xep_loai(diem):
    if diem < 5.0:
        return 'Y'
    elif diem < 6.5:
        return 'TB'
    elif diem < 8.0:
        return 'K'
    elif diem < 9.0:
        return 'G'
    else:
        return 'XS'

# Áp dụng hàm xếp loại cho từng năm học
df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)

# Hiển thị kết quả điểm và xếp loại để đối chiếu
display(df[['TBM1', 'XL1', 'TBM2', 'XL2', 'TBM3', 'XL3']].head())

   TBM1 XL1  TBM2 XL2  TBM3 XL3
0  7.00   K  7.54   K  7.06   K
1  4.69   Y  5.47  TB  4.70   Y
2  5.77  TB  5.38  TB  4.33   Y
3  6.21  TB  5.20  TB  6.03  TB
4  6.50   K  6.36  TB  7.01   K

In [ ]:
# CÂU 9: CHUYỂN ĐỔI SANG THANG ĐIỂM 4 CỦA MỸ (MIN-MAX NORMALIZATION)

# Chuyển đổi từ thang điểm 10 sang thang điểm 4
df['US_TBM1'] = (df['TBM1'] / 10) * 4
df['US_TBM2'] = (df['TBM2'] / 10) * 4
df['US_TBM3'] = (df['TBM3'] / 10) * 4

# Hiển thị kết quả điểm hệ Việt Nam và hệ Mỹ để kiểm tra
display(df[['TBM1', 'US_TBM1', 'TBM2', 'US_TBM2', 'TBM3', 'US_TBM3']].head())

   TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
0  7.00    2.800  7.54    3.016  7.06    2.824
1  4.69    1.876  5.47    2.188  4.70    1.880
2  5.77    2.308  5.38    2.152  4.33    1.732
3  6.21    2.484  5.20    2.080  6.03    2.412
4  6.50    2.600  6.36    2.544  7.01    2.804

In [ ]:
# CÂU 10: TẠO BIẾN KẾT QUẢ XÉT TUYỂN (KQXT)

# Nếu TBM3 >= 5.0 thì KQXT = 1 (Đạt), ngược lại KQXT = 0 (Không đạt)
df['KQXT'] = df['TBM3'].apply(lambda x: 1 if x >= 5.0 else 0)

# Thống kê số lượng thí sinh Đạt và Không đạt
print("--- Thống kê kết quả xét tuyển (1: Đạt, 0: Trượt) ---")
print(df['KQXT'].value_counts())

# Hiển thị thử vài dòng kết quả
display(df[['TBM3', 'KQXT']].head())

--- Thống kê kết quả xét tuyển (1: Đạt, 0: Trượt) ---
KQXT
1    92
0     8
Name: count, dtype: int64

   TBM3  KQXT
0  7.06     1
1  4.70     0
2  4.33     0
3  6.03     1
4  7.01     1

In [ ]:
# CÂU 11: LƯU TRỮ VÀ XUẤT DỮ LIỆU ĐÃ XỬ LÝ

# Xuất DataFrame hoàn chỉnh ra file CSV theo đúng tên yêu cầu của đề bài
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)

print("-> Đã thực hiện câu 11: Lưu và xuất file 'processed_dulieuxettuyendaihoc.csv' thành công!")
print("Số lượng dòng và cột hiện tại của file:", df.shape)

-> Đã thực hiện câu 11: Lưu và xuất file 'processed_dulieuxettuyendaihoc.csv' thành công!
Số lượng dòng và cột hiện tại của file: (100, 66)

In [ ]:
# Chạy ô này để xuất dữ liệu ra file csv
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
print("Đã tạo file thành công!")

Đã tạo file thành công!